In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
dataset = pd.read_csv("E:\_ML\statistics\housing.csv")
final_data = dataset.dropna()

<>:1: SyntaxWarning: invalid escape sequence '\_'
<>:1: SyntaxWarning: invalid escape sequence '\_'
C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\4150025364.py:1: SyntaxWarning: invalid escape sequence '\_'
  dataset = pd.read_csv("E:\_ML\statistics\housing.csv")


In [21]:
final_data['total_rooms'] = np.log(final_data['total_rooms'] + 1)
final_data['total_bedrooms'] = np.log(final_data['total_bedrooms'] + 1)
final_data['population'] = np.log(final_data['total_rooms'] + 1)
final_data['households'] = np.log(final_data['households'] + 1)

C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\634444932.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data['total_rooms'] = np.log(final_data['total_rooms'] + 1)
C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\634444932.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data['total_bedrooms'] = np.log(final_data['total_bedrooms'] + 1)
C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\634444932.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Dat

In [22]:
final_data['total_rooms'] = np.log(final_data['total_rooms'] + 1)
final_data['total_bedrooms'] = np.log(final_data['total_bedrooms'] + 1)
final_data['population'] = np.log(final_data['total_rooms'] + 1)
final_data['households'] = np.log(final_data['households'] + 1)

C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\634444932.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data['total_rooms'] = np.log(final_data['total_rooms'] + 1)
C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\634444932.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data['total_bedrooms'] = np.log(final_data['total_bedrooms'] + 1)
C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\634444932.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Dat

In [23]:
final_data['bedroom_ratio'] = final_data['total_bedrooms'] / final_data['total_rooms']
final_data['household_rooms'] = final_data['total_rooms'] / final_data['households']

C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\2392057115.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data['bedroom_ratio'] = final_data['total_bedrooms'] / final_data['total_rooms']
C:\Users\Sheik\AppData\Local\Temp\ipykernel_16988\2392057115.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data['household_rooms'] = final_data['total_rooms'] / final_data['households']


In [24]:
X = np.array(final_data.drop(['median_house_value'], axis = 1))
y = np.array(final_data['median_house_value'])

In [25]:
final_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0     2.051692        1.769435   
1        -122.22     37.86                21.0     2.289282        2.080617   
2        -122.24     37.85                52.0     2.115250        1.832945   
3        -122.25     37.85                52.0     2.098104        1.866222   
4        -122.25     37.85                52.0     2.127649        1.892864   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0     2.130394        1.935416   
20636    -121.21     39.49                18.0     2.021312        1.794635   
20637    -121.22     39.43                17.0     2.165723        1.972164   
20638    -121.32     39.43                18.0     2.143457        1.948216   
20639    -121.24     39.37                16.0     2.189681        2.004835   

       population  households  median_income  median_house_value  \
0        1.115696    1.765448         8.3252            452600.0   
1        1.190669    2.084169         8.3014            358500.0   
2        1.136309    1.821607         7.2574            352100.0   
3        1.130790    1.855302         5.6431            341300.0   
4        1.140282    1.881095         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635    1.141159    1.917234         1.5603             78100.0   
20636    1.105691    1.748318         2.5568             77100.0   
20637    1.152381    1.956291         1.7000             92300.0   
20638    1.145323    1.925406         1.8672             84700.0   
20639    1.159921    1.984411         2.3886             89400.0   

      ocean_proximity  bedroom_ratio  household_rooms  
0            NEAR BAY       0.862427         1.162137  
1            NEAR BAY       0.908851         1.098415  
2            NEAR BAY       0.866538         1.161200  
3            NEAR BAY       0.889480         1.130869  
4            NEAR BAY       0.889651         1.131070  
...               ...            ...              ...  
20635          INLAND       0.908478         1.111181  
20636          INLAND       0.887857         1.156146  
20637          INLAND       0.910626         1.107056  
20638          INLAND       0.908913         1.113249  
20639          INLAND       0.915583         1.103441  

[20433 rows x 12 columns]

In [26]:
X

array([[-122.23, 37.88, 41.0, ..., 'NEAR BAY', 0.8624268587907388,
        1.1621372273510282],
       [-122.22, 37.86, 21.0, ..., 'NEAR BAY', 0.9088513181363433,
        1.0984149783418957],
       [-122.24, 37.85, 52.0, ..., 'NEAR BAY', 0.8665384126288618,
        1.1611999351882432],
       ...,
       [-121.22, 39.43, 17.0, ..., 'INLAND', 0.910626002739234,
        1.1070556629364456],
       [-121.32, 39.43, 18.0, ..., 'INLAND', 0.9089129588815436,
        1.113249191564577],
       [-121.24, 39.37, 16.0, ..., 'INLAND', 0.9155832084935954,
        1.1034411559872122]], dtype=object)

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [28]:
X

array([[0.0, 0.0, 0.0, ..., 8.3252, 0.8624268587907388,
        1.1621372273510282],
       [0.0, 0.0, 0.0, ..., 8.3014, 0.9088513181363433,
        1.0984149783418957],
       [0.0, 0.0, 0.0, ..., 7.2574, 0.8665384126288618,
        1.1611999351882432],
       ...,
       [0.0, 1.0, 0.0, ..., 1.7, 0.910626002739234, 1.1070556629364456],
       [0.0, 1.0, 0.0, ..., 1.8672, 0.9089129588815436,
        1.113249191564577],
       [0.0, 1.0, 0.0, ..., 2.3886, 0.9155832084935954,
        1.1034411559872122]], dtype=object)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [30]:
from sklearn.linear_model import LinearRegression

# X_train, y_train = final_data.drop(['median_house_value'], axis=1), final_data['median_house_value']

reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [35]:
X_test

array([[1.0, 0.0, 0.0, ..., 7.7116, 0.8969417919579431,
        1.1185489074926003],
       [1.0, 0.0, 0.0, ..., 5.2962, 0.8887941118281746,
        1.1260042249747462],
       [1.0, 0.0, 0.0, ..., 2.7961, 0.9136287700483839,
        1.0948649314518417],
       ...,
       [0.0, 0.0, 0.0, ..., 1.4952, 0.9148205509524932,
        1.1127318705231544],
       [0.0, 0.0, 0.0, ..., 8.2436, 0.8890065070123796,
        1.1250967220883255],
       [1.0, 0.0, 0.0, ..., 5.1463, 0.888444513456082,
        1.1319283555704842]], dtype=object)

In [31]:
reg.score(X_test, y_test)

0.6403140604262303

In [32]:
from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor()

forest.fit(X_train, y_train)

RandomForestRegressor()

In [34]:
forest.score(X_test, y_test)

0.8205485532880565

In [37]:
y_pred = forest.predict(X_test)